
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module test(

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

reg [3:0] a;

reg [3:0] cnt;


//=======================================================
//  Structural coding
//=======================================================

always @(negedge KEY[0])
begin

	a = a + cnt;

end

always @(negedge KEY[1])
begin

	cnt = cnt + 1'b1;

end

SEG_HEX u0
(
	.iDIG(a),
	.oHEX_D(HEX0)
);

SEG_HEX u1
(
	.iDIG(a),
	.oHEX_D(HEX1)
);
SEG_HEX u2
(
	.iDIG(a),
	.oHEX_D(HEX2)
);
SEG_HEX u3
(
	.iDIG(a),
	.oHEX_D(HEX3)
);
SEG_HEX u4
(
	.iDIG(a),
	.oHEX_D(HEX4)
);
SEG_HEX u5
(
	.iDIG(a),
	.oHEX_D(HEX5)
);


endmodule
